using System.Collections.ObjectModel;
using CgCar.Core.Data;
using CgCar.Core.Models;
using CgCar.Core.Navigation;
using CgCar.Core.Services;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;

namespace CgCar.Core.ViewModels;

/// <summary>Page 2: the vehicles of one category, with search, add, edit and delete.</summary>
public partial class VehicleListViewModel(
    IVehicleRepository repository,
    INavigationService navigation,
    IDialogService dialogs,
    IPhotoService photos) : ObservableObject, INavigationParameterReceiver
{
    /// <summary>Everything loaded for the category; <see cref="Vehicles"/> is the filtered view of it.</summary>
    private List<VehicleListItem> _allVehicles = [];

    public ObservableCollection<VehicleListItem> Vehicles { get; } = [];

    [ObservableProperty]
    public partial VehicleCategory Category { get; private set; }

    [ObservableProperty]
    public partial string Title { get; private set; } = string.Empty;

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(EmptyMessage))]
    public partial string SearchText { get; set; } = string.Empty;

    public string EmptyMessage => string.IsNullOrWhiteSpace(SearchText)
        ? $"No {Title.ToLowerInvariant()} yet.\nTap + to add one."
        : "No vehicles match your search.";

    public void ReceiveParameters(IDictionary<string, object> parameters)
    {
        if (parameters.TryGetValue(NavigationParameters.Category, out var value) && value is VehicleCategory category)
        {
            Category = category;
            Title = category.DisplayName();
            OnPropertyChanged(nameof(EmptyMessage));
        }
    }

    /// <summary>Runs every time the page appears, so the list reflects changes made on the edit page.</summary>
    [RelayCommand]
    private async Task LoadAsync()
    {
        try
        {
            var vehicles = await repository.GetByCategoryAsync(Category);
            _allVehicles = vehicles
                .Select(v => new VehicleListItem(v, photos.GetFullPath(v.PhotoPath), EditAsync, DeleteAsync))
                .ToList();
            ApplyFilter();
        }
        catch (Exception ex)
        {
            await dialogs.AlertAsync("Error", $"Could not load the vehicles. {ex.Message}");
        }
    }

    // Generated by CommunityToolkit.Mvvm: called whenever SearchText changes (i.e. on every keystroke).
    partial void OnSearchTextChanged(string value) => ApplyFilter();

    /// <summary>
    /// Filters in memory: a category holds few enough vehicles that this is instant, and it avoids a query per keystroke.
    /// Plates are compared in normalized form, so searching "ικα 12" finds "IKA-1234".
    /// </summary>
    private void ApplyFilter()
    {
        var term = SearchText.Trim();
        var plateTerm = LicensePlate.Normalize(term);

        var matches = term.Length == 0
            ? _allVehicles
            : _allVehicles.Where(item =>
                item.Vehicle.Brand.Contains(term, StringComparison.CurrentCultureIgnoreCase) ||
                item.Vehicle.Model.Contains(term, StringComparison.CurrentCultureIgnoreCase) ||
                (plateTerm.Length > 0 && item.Vehicle.PlateNumber.Contains(plateTerm, StringComparison.Ordinal)));

        Vehicles.Clear();
        foreach (var item in matches)
        {
            Vehicles.Add(item);
        }
    }

    [RelayCommand]
    private Task AddAsync() =>
        navigation.GoToAsync(Routes.VehicleEdit, new Dictionary<string, object>
        {
            [NavigationParameters.Category] = Category,
        });

    // Invoked through each row's EditCommand / DeleteCommand (see VehicleListItem).
    private Task EditAsync(VehicleListItem item) =>
        navigation.GoToAsync(Routes.VehicleEdit, new Dictionary<string, object>
        {
            [NavigationParameters.VehicleId] = item.Vehicle.Id,
        });

    private async Task DeleteAsync(VehicleListItem item)
    {
        var confirmed = await dialogs.ConfirmAsync(
            "Delete vehicle",
            $"Delete {item.Title} ({item.PlateNumber})? This cannot be undone.",
            "Delete",
            "Cancel");

        if (!confirmed)
        {
            return;
        }

        try
        {
            await repository.DeleteAsync(item.Vehicle.Id);
            photos.DeletePhoto(item.Vehicle.PhotoPath);

            _allVehicles.Remove(item);
            Vehicles.Remove(item);
            await dialogs.ToastAsync("Vehicle deleted");
        }
        catch (Exception ex)
        {
            await dialogs.AlertAsync("Error", $"Could not delete the vehicle. {ex.Message}");
        }
    }
}
